const APP_TITLE = 'MindBridge Global';
const APP_SUBTITLE = 'Phase 1 prototype for an integrated AI-powered global mental health ecosystem';
const SPREADSHEET_LINK_OR_ID = 'https://docs.google.com/spreadsheets/d/1ZtYIof8z94Nf8BtKO2iTF5NM-pob5WS5xtk1fMtf0RE/edit?gid=0#gid=0';
const SESSION_TTL_SECONDS = 21600;
const TELEGRAM_NOTIFICATIONS_ENABLED = false;
const TELEGRAM_BOT_TOKEN = '';
const TELEGRAM_CHAT_ID = '';
const AI_ASSIST_ENABLED = true;
const AI_PROVIDER = 'openai';
const AI_MODEL = 'gpt-4.1';
const AI_API_KEY_PROPERTY = 'OPENAI_API_KEY';

const SHEET_SCHEMAS = {
  Patient_Registration: [
    'registered_at',
    'patient_code',
    'patient_label',
    'contact_phone',
    'emergency_contact',
    'caregiver_name',
    'health_coverage',
    'reason_for_first_visit',
    'consent_acknowledged',
    'registration_source',
    'patient_portal_code',
    'family_portal_code'
  ],
  Patient_Checkin: [
    'created_at',
    'case_id',
    'patient_code',
    'respondent_name',
    'informant_type',
    'preferred_language',
    'visit_date',
    'main_concern',
    'current_symptoms',
    'chatbot_transcript',
    'distress_level',
    'bprs_total_score',
    'bprs_interpretation',
    'safety_concern',
    'family_caregiver_support',
    'barrier_to_care',
    'additional_notes',
    'risk_flag',
    'risk_reasons',
    'visit_purpose',
    'reason_for_visit',
    'appointment_code',
    'accompanying_person',
    'payment_coverage',
    'local_rule_flag',
    'local_rule_reasons',
    'ai_priority_flag',
    'ai_confidence',
    'ai_reasons',
    'triage_destination',
    'recommended_service',
    'triage_urgency',
    'emergency_action',
    'self_help_guidance',
    'mdt_focus',
    'community_support_signal',
    'follow_up_window',
    'priority_for_review',
    'ai_validation_status'
  ],
  Service_Followup: [
    'requested_at',
    'case_id',
    'patient_code',
    'requester_type',
    'service_type',
    'appointment_code',
    'medication_need',
    'current_symptoms',
    'main_concern',
    'caregiver_concern',
    'social_problem',
    'payment_coverage',
    'today_support_needed',
    'urgency_level',
    'risk_flag',
    'risk_reasons',
    'local_rule_flag',
    'local_rule_reasons',
    'ai_priority_flag',
    'ai_confidence',
    'ai_reasons',
    'priority_for_review',
    'ai_validation_status'
  ],
  Community_Referral: [
    'referred_at',
    'case_id',
    'patient_code',
    'informant_name',
    'relationship_to_patient',
    'contact_phone',
    'visit_purpose',
    'reason_for_referral',
    'observed_behavior',
    'main_concern',
    'current_symptoms',
    'safety_concern',
    'family_caregiver_support',
    'barrier_to_care',
    'additional_notes',
    'risk_flag',
    'risk_reasons',
    'local_rule_flag',
    'local_rule_reasons',
    'ai_priority_flag',
    'ai_confidence',
    'ai_reasons',
    'priority_for_review',
    'ai_validation_status'
  ],
  Clinical_Review: [
    'reviewed_at',
    'case_id',
    'reviewer_name',
    'diagnosis_group',
    'bprs_total_score',
    'bprs_interpretation',
    'medication_adherence',
    'relapse_warning_signs',
    'suicide_self_harm_concern',
    'violence_risk',
    'substance_use_concern',
    'clinical_notes',
    'risk_flag',
    'risk_reasons'
  ],
  Psychological_Review: [
    'reviewed_at',
    'case_id',
    'reviewer_name',
    'stress_level',
    'coping_ability',
    'trauma_grief_concern',
    'therapy_need',
    'sleep_problem',
    'emotional_regulation',
    'psychological_notes',
    'risk_flag',
    'risk_reasons'
  ],
  Psychosocial_Review: [
    'reviewed_at',
    'case_id',
    'reviewer_name',
    'family_conflict',
    'debt_financial_stress',
    'housing_problem',
    'caregiver_support',
    'welfare_need',
    'stigma',
    'violence_abuse',
    'community_support',
    'psychosocial_notes',
    'risk_flag',
    'risk_reasons'
  ],
  MDT_Care_Plan: [
    'updated_at',
    'case_id',
    'meeting_date',
    'main_care_goal',
    'clinical_plan',
    'psychological_plan',
    'social_intervention_plan',
    'rehabilitation_plan',
    'referral_plan',
    'discharge_readiness',
    'team_members',
    'overall_risk_flag'
  ],
  Minimum_Necessary_Handoff: [
    'updated_at',
    'case_id',
    'reviewed_by',
    'consent_status',
    'caregiver_involvement',
    'public_sector_share',
    'private_partner_share',
    'community_follow_up_share',
    'handoff_ready',
    'next_step_owner',
    'next_contact_window',
    'minimum_necessary_summary',
    'crisis_safety_summary',
    'do_not_share'
  ],
  Public_Coordination: [
    'updated_at',
    'case_id',
    'agency_name',
    'coordination_type',
    'urgency_level',
    'referral_reason',
    'shared_information',
    'requested_action',
    'meeting_date',
    'coordination_status',
    'notes'
  ],
  Private_Coordination: [
    'updated_at',
    'case_id',
    'organization_name',
    'support_domain',
    'urgency_level',
    'referral_reason',
    'support_needs',
    'requested_action',
    'meeting_date',
    'coordination_status',
    'notes'
  ],
  Follow_Up: [
    'updated_at',
    'case_id',
    'follow_up_due_date',
    'responsible_staff',
    'referral_destination',
    'follow_up_status',
    'barrier_after_discharge',
    'outcome',
    'escalation_needed',
    'follow_up_notes',
    'risk_flag',
    'risk_reasons'
  ],
  Users: [
    'email',
    'display_name',
    'role',
    'profession',
    'active',
    'login_username',
    'login_password',
    'allowed_portal',
    'organization'
  ],
  Portal_Access: [
    'portal_type',
    'patient_code',
    'display_name',
    'access_code',
    'active'
  ],
  Alert_Queue: [
    'queued_at',
    'case_id',
    'patient_code',
    'informant_type',
    'visit_purpose',
    'queue_priority',
    'risk_flag',
    'triage_destination',
    'triage_urgency',
    'bprs_total_score',
    'bprs_interpretation',
    'summary',
    'telegram_status',
    'telegram_response',
    'handled_status'
  ],
  AI_Screening_Log: [
    'screened_at',
    'case_id',
    'patient_code',
    'source_form',
    'screening_status',
    'ai_provider',
    'ai_model',
    'local_rule_flag',
    'ai_priority_flag',
    'priority_for_review',
    'agreement_status',
    'ai_confidence',
    'human_review_required',
    'monitor_group',
    'bias_watch_status',
    'ai_summary',
    'ai_reasons',
    'triage_destination',
    'recommended_service',
    'triage_urgency',
    'emergency_action',
    'raw_output'
  ],
  Cases_Master: [
    'case_id',
    'patient_code',
    'entry_point',
    'entry_label',
    'current_stage',
    'journey_status',
    'priority_flag',
    'queue_priority',
    'last_touchpoint_at',
    'last_touchpoint_type',
    'owner_team',
    'network_status',
    'follow_up_status',
    'handoff_status',
    'consent_status',
    'next_action',
    'latest_summary'
  ],
  Case_Timeline: [
    'event_at',
    'case_id',
    'patient_code',
    'event_type',
    'stage',
    'actor',
    'summary',
    'risk_flag',
    'queue_priority'
  ],
  Dashboard: [
    'section',
    'metric',
    'value',
    'updated_at',
    'notes'
  ]
};

const OPTION_SETS = {
  registrationSource: ['Self registration', 'Staff-assisted registration', 'Caregiver-assisted registration'],
  consentOptions: ['Yes', 'Pending discussion'],
  informantType: ['Patient', 'Family/Caregiver', 'Staff'],
  requesterType: ['Patient', 'Family/Caregiver', 'Staff'],
  preferredLanguage: ['English', 'Thai', 'Chinese (Simplified)', 'Hindi', 'Urdu'],
  visitPurpose: ['Scheduled appointment (มาตามนัด)', 'Walk-in', 'ER urgent (ER ด่วน)', 'Referral', 'Community follow-up', 'Digital self-screening'],
  reasonForVisit: [
    'See psychiatrist / doctor',
    'Follow-up appointment',
    'Medication refill',
    'See psychologist',
    'See psychiatric social worker',
    'Vocational training / rehabilitation',
    'Group activity / therapy activity',
    'Welfare / legal support',
    'Self-screening / AI triage',
    'Other'
  ],
  paymentCoverage: ['Universal coverage', 'Social security', 'Civil servant benefit', 'Self-pay', 'Other'],
  medicationNeed: ['No medication issue', 'Need refill soon', 'Out of medication', 'Adherence concern'],
  serviceType: [
    'Appointment follow-up',
    'Medication refill',
    'Psychology visit',
    'Social work visit',
    'Rehabilitation / OT',
    'Group activity',
    'Home visit coordination',
    'Other'
  ],
  supportNeed: [
    'Routine review',
    'Medication refill only',
    'Psychology support',
    'Social work support',
    'Rehabilitation support',
    'Urgent review'
  ],
  urgencyLevel: ['Routine', 'Priority', 'Immediate'],
  relationshipType: [
    'Neighbor',
    'Community volunteer',
    'Village health volunteer',
    'Community leader',
    'Employer',
    'Teacher / school staff',
    'Other'
  ],
  coordinationType: [
    'Home visit coordination',
    'Welfare support',
    'Legal / protection support',
    'Shelter placement',
    'School support',
    'Medication follow-up',
    'Case conference',
    'Other'
  ],
  supportDomain: [
    'Vocational support',
    'Employment support',
    'Foundation / welfare support',
    'Private shelter',
    'Community activity',
    'Private clinic / pharmacy linkage',
    'Other'
  ],
  coordinationStatus: ['Draft', 'Requested', 'Accepted', 'In progress', 'Completed', 'Closed'],
  distressLevel: ['Low', 'Moderate', 'High', 'Severe'],
  safetyConcern: ['None', 'Monitor', 'Urgent', 'Suicide/Self-harm concern'],
  familySupport: ['Strong', 'Limited', 'No caregiver available'],
  barrierToCare: ['None', 'Transportation', 'Cost', 'Time/Work', 'Stigma', 'Housing', 'Other'],
  diagnosisGroup: [
    'Mood disorder',
    'Psychotic disorder',
    'Anxiety-related disorder',
    'Substance-related disorder',
    'Neurocognitive condition',
    'Other/Undifferentiated'
  ],
  medicationAdherence: ['Adherent', 'Partially adherent', 'Not adherent', 'Not applicable'],
  relapseWarning: ['None', 'Mild', 'Moderate', 'Severe'],
  suicideConcern: ['None', 'Passive thoughts', 'Active concern', 'Immediate risk'],
  violenceRisk: ['None', 'Low', 'Moderate', 'High'],
  substanceConcern: ['None', 'Monitor', 'Active concern'],
  stressLevel: ['Low', 'Moderate', 'High', 'Severe'],
  copingAbility: ['Strong', 'Adequate', 'Reduced', 'Poor'],
  traumaConcern: ['None', 'Monitor', 'Active concern'],
  therapyNeed: ['Routine', 'Soon', 'Urgent'],
  sleepProblem: ['None', 'Mild', 'Moderate', 'Severe'],
  emotionalRegulation: ['Stable', 'Some difficulty', 'Significant difficulty'],
  familyConflict: ['None', 'Mild', 'Moderate', 'Severe'],
  debtStress: ['None', 'Mild', 'Moderate', 'Severe'],
  housingProblem: ['Stable', 'Unstable', 'Unsafe', 'Homeless risk'],
  caregiverSupport: ['Adequate', 'Limited', 'No caregiver available'],
  welfareNeed: ['None', 'Routine support', 'Urgent support'],
  stigma: ['None', 'Mild', 'Moderate', 'Severe'],
  violenceAbuse: ['None', 'Past concern', 'Current concern', 'Immediate danger'],
  communitySupport: ['Strong', 'Available', 'Limited', 'None'],
  dischargeReadiness: ['Ready', 'Needs follow-up plan', 'Needs stabilization'],
  followUpStatus: ['Pending', 'Scheduled', 'Completed', 'Missed', 'Escalated'],
  barrierAfterDischarge: ['None', 'Transportation', 'Cost', 'Medication access', 'Family support', 'Housing', 'Stigma', 'Other'],
  escalationNeeded: ['No', 'Monitor', 'Yes - urgent'],
  consentStatus: ['Confirmed', 'Pending discussion', 'Emergency exception only'],
  caregiverInvolvement: ['Patient only', 'Family involved', 'Family not involved', 'To be discussed'],
  shareBoundary: ['Do not share', 'Share minimum necessary', 'Share after direct confirmation'],
  handoffReady: ['Draft', 'Ready to send', 'Sent', 'Needs review'],
  nextContactWindow: ['Same day', 'Within 24 hours', 'Within 72 hours', 'At next appointment']
};

